AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  crd-with-awshealthlake
  Sample SAM Template to Determine Coverage Requirements Discovery using CDS Hooks with AWS HealthLake

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
      Cors:
          AllowMethods: "'GET,POST,OPTIONS'"
          AllowHeaders: "'*'"
          AllowOrigin: "'*'"


Resources:
  
  HealthDatastore:
    Type: AWS::HealthLake::FHIRDatastore
    Properties: 
     DatastoreName: "HealthDatastore"
     DatastoreTypeVersion: "R4"
     PreloadDataConfig: 
          PreloadDataType: "SYNTHEA"
          
  cdsDemoServicesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/cdshandler
      Handler: app.get_cds_services
      Runtime: python3.8
      Events:
        Api:
          Type: Api
          Properties:
            Path: /cds-services
            Method: GET

  cqlQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/patientconditions
      Handler: cql-app.runCQLQuery
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: API to execute a CQL(Clinical Quality Language) query that reads FHIR resources from HL
      Policies: 
        - AmazonHealthLakeReadOnlyAccess
      Environment:
        Variables:
          SERVICE: 'healthlake'
          DATASTOREID: !GetAtt HealthDatastore.DatastoreId
      Events:
        Api:
          Type: Api
          Properties:
            Path: /cds-services/cql-executor
            Method: POST
   
      
  cqlQueryOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/patientorder
      Handler: cql-order-app.validatePriorAuth
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: API to execute a CQL(Clinical Quality Language) query that reads FHIR resources from HL
      Policies: 
        - AmazonHealthLakeReadOnlyAccess
      Environment:
        Variables:
          SERVICE: 'healthlake'
          DATASTOREID: !GetAtt HealthDatastore.DatastoreId    
      Events:
        Api:
          Type: Api
          Properties:
            Path: /cds-services/order-executor
            Method: POST
   
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CDSDemoServicesApi:
    Description: "API Gateway endpoint URL for Prod stage for CDS Hook services"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cds-services"

  CQLQueryExecutionApi:
    Description: "API Gateway endpoint URL for Prod stage for patient view CDS Hooks"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cds-services/cql-executor"
  
  PatientNotesEntryApi:
    Description: "API Gateway endpoint URL for Prod stage for entering patient notes"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cds-services/order-executor"
